config/routes.rb
Rails.application.routes.draw do
  resources :microposts
  resources :users
  resources :events
  get 'home/index'

  get 'home/about'

  get 'home/contact'

  get 'home/faq'

  root 'home#index'
  
  get '/about' => 'home#about'
  
  post '/question' => 'home#temp'
  
  get '/questions/:id' => 'home#questions'
  

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :location, :start, :end)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
  
  def contact
  end
  
  def faq
  end
  
  def temp
    redirect_to root_path
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.datetime_select :end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Location</th>
      <th>Start</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.location %></td>
        <td><%= event.start %></td>
        <td><%= event.end %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @event.end %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/faq.html.erb
<h1>Home#faq</h1>
<p>Find me in app/views/home/faq.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
		<div class="media">
			<div class="media-left">
				<a href="#">
					<img class="media-object" src="http://www.gravatar.com/avatar/424242">
				</a>
			</div>
			<div class="media-body">
			 <h4 class="media-heading">user@email.com asked:</h4>
			 Lorem ipsum folor sit amte, conseturtur adipisicn elit. Dolore, epedita. Ullam
			 voluptatem suscipit, modit curruti assumenda fugait a qui ex dolorum , arhcitecto
			 nulla quia accuatimu , vitae consecturue cum doloribus debitis.
			</div>
		</div>	

app/views/home/questions.html.erb
<div class="container">
	<div class="lead">
		<div class="media">
			<div class="media-left">
				<a href="#">
					<img class="media-object" src="http://www.gravatar.com/avatar/424242">
				</a>
			</div>
			<div class="media-body">
			 <h4 class="media-heading">user@email.com asked:</h4>
			 Lorem ipsum folor sit amte, conseturtur adipisicn elit. Dolore, epedita. Ullam
			 voluptatem suscipit, modit curruti assumenda fugait a qui ex dolorum , arhcitecto
			 nulla quia accuatimu , vitae consecturue cum doloribus debitis.
			</div>
		</div>	
	</div>
			<div class="media mt-3">
			<div class="media-left">
				<a href="#">
					<img class="media-object" src="http://www.gravatar.com/avatar/424242">
				</a>
			</div>
			<div class="media-body">
			 <h4 class="media-heading">user@email.com asked:</h4>
			 Lorem ipsum folor sit amte, conseturtur adipisicn elit. Dolore, epedita. Ullam
			 voluptatem suscipit, modit curruti assumenda fugait a qui ex dolorum , arhcitecto
			 nulla quia accuatimu , vitae consecturue cum doloribus debitis.
			</div>
		</div>
		<div class="media mt-3">
			<div class="media-left">
				<a href="#">
					<img class="media-object" src="http://www.gravatar.com/avatar/424242">
				</a>
			</div>
			<div class="media-body">
			 <h4 class="media-heading">user@email.com asked:</h4>
			 Lorem ipsum folor sit amte, conseturtur adipisicn elit. Dolore, epedita. Ullam
			 voluptatem suscipit, modit curruti assumenda fugait a qui ex dolorum , arhcitecto
			 nulla quia accuatimu , vitae consecturue cum doloribus debitis.
			</div>
		</div>
		<div class="media mt-3">
			<div class="media-left">
				<a href="#">
					<img class="media-object" src="http://www.gravatar.com/avatar/424242">
				</a>
			</div>
			<div class="media-body">
			 <h4 class="media-heading">user@email.com asked:</h4>
			 Lorem ipsum folor sit amte, conseturtur adipisicn elit. Dolore, epedita. Ullam
			 voluptatem suscipit, modit curruti assumenda fugait a qui ex dolorum , arhcitecto
			 nulla quia accuatimu , vitae consecturue cum doloribus debitis.
			</div>
		</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Byars Youth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<!-- Latest compiled and minified CSS -->
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
	<!-- Optional theme -->
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "shared/navbar" %>

<div class="container">
	<%= yield %>
</div>

<%= render "shared/new_question_form" %>

<%= render "shared/footer" %>

</body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/shared/_footer.html.erb
    <footer class="footer">
      <div class="navbar navbar-default navbar-fixed-bottom">
      	<div class="container-fluid">
      		<div class="row">
      			<div class="col-xs-6 col-md-4" style="text-align: left;">
      			</div>	
      			<div class="col-xs-6 col-md-4" style="text-align: center;">
                	<h4>
                		Our Background &amp; Our Circumstances May Have Influenced Who We Are, 
		                	However We Are Still Responsible 
		                	For Who We Become.
		            </h4>
                	
                	<h4><b>B</b>etter <b>Y</b>outh <b>A</b>wareness &amp; <b>R</b>esponse <b>S</b>ervices</h4>
                </div>
                <div class="col-xs-6 col-md-4" style="text-align: center;">	
					<a  class="navbar-right" href="/home/index" title="Byars Youth">
					  	 Byars Youth Copyright <%= Time.current.year %>
				         <img style="max-width:70%; margin-top: 15px; padding-right=0px;" class="img-responsive" src="/assets/BYARSsmaller_LOGO.ico" alt="Byars Youth" > 
				    </a>
			    </div>
			 </div> 
		</div>
      </div>
    </footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a style="padding-right=0px" class="navbar-brand" href="/home/index" title="Byars Youth">
		        <img style="max-width:60%; margin-top: -7px; padding-right=0px;" class="img-responsive" src="/assets/BYARSIcon.ico" alt="Byars Youth" > 
		   </a> 
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-left">
				<li> <a class="navbar-brand" href="/home/index">Home</a> </li>
				<li> <a class="navbar-brand" href="/home/about">About Us</a> </li>
				<li> <a class="navbar-brand" href="/home/contact">Contact</a> </li>
				<li> <a class="navbar-brand" href="/home/faq">Faq</a> </li>
				<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"/>
								</a>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#">Action</a>
									</li>
									<li>
										<a href="#">Another action</a>
									</li>
									<li>
										<a href="#">Something else here</a>
									</li>
									<li class="divider"/>
									<li class="dropdown-header">Nav header</li>
									<li>
										<a href="#">Separated link</a>
									</li>
									<li>
										<a href="#">One more separated link</a>
									</li> 
								</ul> 
				</li>
			</ul>	
			<ul class="nav navbar-nav navbar-right">
				<li>
						<form>
							<a href="#" class="btn btn-success navbar-btn btn-sm" data-toggle="modal" data-target="#myModal" >
								Ask Question
							</a>
						</form>	
				</li>
			</ul>
		</div>
	</div> 
</nav>

app/views/shared/_new_question_form.html.erb
<div class="modal fade" id="myModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Question</h4>
      </div>
      <%= form_for :question, url: '/question', html: { class: 'form-horizontal' } do %>
      <!-- <form class="form-horizontal" action="/questions" method="POST"> -->
      <div class="modal-body">
        	<div class="form-group">
        		<label for="inputEmail" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                	<input type="email" name="email" class="form-control" id="inputEmail" placeholder="Email" required>
                </div>        	
        	</div>	
        	<div class="form-group">
        		<label for="inputQuestion" class="col-sm-2 control-label">Question</label>
        		 <div class="col-sm-10">
                	<textarea class="form-control" name="question_body" id="inputQuestion" placeholder="What would you like to know ?" required></textarea>
                </div> 
        	</div>	
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
      <!-- </form> -->
      <% end %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>